// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestauranteSaaS.Api.Infrastructure.Persistence;

#nullable disable

namespace RestauranteSaaS.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717061703_InitialMultitenant")]
    partial class InitialMultitenant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.AsignacionInquilino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<Guid>("IdInquilino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_inquilino");

                    b.Property<Guid>("IdRoleInquilino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_rol_inquilino");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("idx_asignaciones_inquilino_activo");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_asignaciones_inquilino_codigo");

                    b.HasIndex("IdInquilino")
                        .HasDatabaseName("idx_asignaciones_inquilino_inquilino");

                    b.HasIndex("IdRoleInquilino")
                        .HasDatabaseName("idx_asignaciones_inquilino_rol");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("idx_asignaciones_inquilino_usuario");

                    b.HasIndex("IdUsuario", "IdInquilino", "IdRoleInquilino")
                        .IsUnique()
                        .HasDatabaseName("ux_asignaciones_inquilino_usuario_inquilino_rol");

                    b.ToTable("asignaciones_inquilino", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.AsignacionInquilinoPermiso", b =>
                {
                    b.Property<Guid>("IdAsignacionInquilino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_asignacion_inquilino");

                    b.Property<Guid>("IdPermisoInquilino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_permiso_inquilino");

                    b.Property<bool>("Permitido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("permitido");

                    b.HasKey("IdAsignacionInquilino", "IdPermisoInquilino");

                    b.HasIndex("IdPermisoInquilino")
                        .HasDatabaseName("idx_asignaciones_inquilino_permisos_permiso");

                    b.ToTable("asignaciones_inquilino_permisos", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.AsignacionOperativa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<Guid>("IdEmpleado")
                        .HasColumnType("uuid")
                        .HasColumnName("id_empleado");

                    b.Property<Guid>("IdRoleOperativo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_rol_operativo");

                    b.Property<Guid>("IdUnidadOperativa")
                        .HasColumnType("uuid")
                        .HasColumnName("id_unidad_operativa");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("idx_asignaciones_operativas_activo");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_asignaciones_operativas_codigo");

                    b.HasIndex("IdEmpleado")
                        .HasDatabaseName("idx_asignaciones_operativas_empleado");

                    b.HasIndex("IdRoleOperativo")
                        .HasDatabaseName("idx_asignaciones_operativas_rol_operativo");

                    b.HasIndex("IdUnidadOperativa")
                        .HasDatabaseName("idx_asignaciones_operativas_unidad_operativa");

                    b.HasIndex("IdEmpleado", "IdUnidadOperativa", "IdRoleOperativo")
                        .IsUnique()
                        .HasDatabaseName("ux_asignaciones_operativas_empleado_unidad_rol");

                    b.ToTable("asignaciones_operativas", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.AsignacionOperativaPermiso", b =>
                {
                    b.Property<Guid>("IdAsignacionOperativa")
                        .HasColumnType("uuid")
                        .HasColumnName("id_asignacion_operativa");

                    b.Property<Guid>("IdPermisoOperativo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_permiso_operativo");

                    b.Property<bool>("Permitido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("permitido");

                    b.HasKey("IdAsignacionOperativa", "IdPermisoOperativo");

                    b.HasIndex("IdPermisoOperativo")
                        .HasDatabaseName("idx_asignaciones_operativas_permisos_permiso");

                    b.ToTable("asignaciones_operativas_permisos", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_clientes_codigo");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("ux_clientes_usuario");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.Direccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("calle");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("colonia");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("estado");

                    b.Property<Guid>("IdInquilino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_inquilino");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitud");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("municipio");

                    b.Property<string>("NumeroExterior")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_exterior");

                    b.Property<string>("NumeroInterior")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_interior");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("pais");

                    b.Property<string>("Referencia")
                        .HasColumnType("text")
                        .HasColumnName("referencia");

                    b.HasKey("Id");

                    b.HasIndex("IdInquilino")
                        .HasDatabaseName("idx_direcciones_inquilino");

                    b.ToTable("direcciones", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<Guid>("IdInquilino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_inquilino");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroEmpleado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_empleado");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("idx_empleados_activo");

                    b.HasIndex("IdInquilino")
                        .HasDatabaseName("idx_empleados_inquilino");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("idx_empleados_usuario");

                    b.HasIndex("IdInquilino", "IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("ux_empleados_inquilino_id_usuario");

                    b.HasIndex("IdInquilino", "NumeroEmpleado")
                        .IsUnique()
                        .HasDatabaseName("ux_empleados_inquilino_numero_empleado");

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.EntidadFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Correo")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correo");

                    b.Property<Guid>("IdInquilino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_inquilino");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razon_social");

                    b.Property<string>("RegimenFiscal")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("regimen_fiscal");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("rfc");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("idx_entidades_fiscales_activo");

                    b.HasIndex("IdInquilino")
                        .HasDatabaseName("idx_entidades_fiscales_inquilino");

                    b.HasIndex("Rfc")
                        .IsUnique()
                        .HasDatabaseName("ux_entidades_fiscales_rfc");

                    b.ToTable("entidades_fiscales", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.Inquilino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("activo")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_inquilinos_codigo");

                    b.ToTable("inquilinos", null, t =>
                        {
                            t.HasCheckConstraint("ck_inquilinos_estado", "estado IN ('activo', 'inactivo', 'suspendido')");
                        });
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.PermisoInquilino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_permisos_inquilino_codigo");

                    b.ToTable("permisos_inquilino", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.PermisoOperativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_permisos_operativos_codigo");

                    b.ToTable("permisos_operativos", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.Restaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("IdInquilino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_inquilino");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("idx_restaurantes_activo");

                    b.HasIndex("IdInquilino")
                        .HasDatabaseName("idx_restaurantes_inquilino");

                    b.HasIndex("IdInquilino", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_restaurantes_inquilino_codigo");

                    b.ToTable("restaurantes", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.RoleInquilino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("IdInquilino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_inquilino");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("idx_roles_inquilino_activo");

                    b.HasIndex("IdInquilino")
                        .HasDatabaseName("idx_roles_inquilino_inquilino");

                    b.HasIndex("IdInquilino", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_inquilino_inquilino_codigo");

                    b.HasIndex("IdInquilino", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_inquilino_inquilino_nombre");

                    b.ToTable("roles_inquilino", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.RoleInquilinoPermiso", b =>
                {
                    b.Property<Guid>("IdRoleInquilino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_rol_inquilino");

                    b.Property<Guid>("IdPermisoInquilino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_permiso_inquilino");

                    b.HasKey("IdRoleInquilino", "IdPermisoInquilino");

                    b.HasIndex("IdPermisoInquilino")
                        .HasDatabaseName("idx_roles_inquilino_permisos_permiso");

                    b.ToTable("roles_inquilino_permisos", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.RoleOperativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("IdInquilino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_inquilino");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdInquilino")
                        .HasDatabaseName("idx_roles_operativos_inquilino");

                    b.HasIndex("IdInquilino", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_operativos_inquilino_nombre");

                    b.ToTable("roles_operativos", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.RoleOperativoPermiso", b =>
                {
                    b.Property<Guid>("IdRoleOperativo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_rol_operativo");

                    b.Property<Guid>("IdPermisoOperativo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_permiso_operativo");

                    b.HasKey("IdRoleOperativo", "IdPermisoOperativo");

                    b.HasIndex("IdPermisoOperativo")
                        .HasDatabaseName("idx_roles_operativos_permisos_permiso");

                    b.ToTable("roles_operativos_permisos", (string)null);
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.UnidadOperativa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<DateTime?>("FechaApertura")
                        .HasColumnType("date")
                        .HasColumnName("fecha_apertura");

                    b.Property<Guid>("IdDireccion")
                        .HasColumnType("uuid")
                        .HasColumnName("id_direccion");

                    b.Property<Guid>("IdEntidadFiscal")
                        .HasColumnType("uuid")
                        .HasColumnName("id_entidad_fiscal");

                    b.Property<Guid>("IdInquilino")
                        .HasColumnType("uuid")
                        .HasColumnName("id_inquilino");

                    b.Property<Guid>("IdRestaurante")
                        .HasColumnType("uuid")
                        .HasColumnName("id_restaurante");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("idx_unidades_operativas_activo");

                    b.HasIndex("IdDireccion")
                        .HasDatabaseName("idx_unidades_operativas_direccion");

                    b.HasIndex("IdEntidadFiscal")
                        .HasDatabaseName("idx_unidades_operativas_entidad_fiscal");

                    b.HasIndex("IdInquilino")
                        .HasDatabaseName("idx_unidades_operativas_inquilino");

                    b.HasIndex("IdRestaurante")
                        .HasDatabaseName("idx_unidades_operativas_restaurante");

                    b.HasIndex("IdInquilino", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_unidades_operativas_inquilino_codigo");

                    b.ToTable("unidades_operativas", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.AsignacionInquilino", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.Inquilino", null)
                        .WithMany()
                        .HasForeignKey("IdInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asignaciones_inquilino_inquilinos");

                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.RoleInquilino", null)
                        .WithMany()
                        .HasForeignKey("IdRoleInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asignaciones_inquilino_roles");

                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asignaciones_inquilino_usuarios");
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.AsignacionInquilinoPermiso", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.AsignacionInquilino", null)
                        .WithMany()
                        .HasForeignKey("IdAsignacionInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asignaciones_inquilino_permisos_asignaciones");

                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.PermisoInquilino", null)
                        .WithMany()
                        .HasForeignKey("IdPermisoInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asignaciones_inquilino_permisos_permisos");
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.AsignacionOperativa", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.Empleado", null)
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asignaciones_operativas_empleados");

                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.RoleOperativo", null)
                        .WithMany()
                        .HasForeignKey("IdRoleOperativo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asignaciones_operativas_roles_operativos");

                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.UnidadOperativa", null)
                        .WithMany()
                        .HasForeignKey("IdUnidadOperativa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asignaciones_operativas_unidades_operativas");
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.AsignacionOperativaPermiso", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.AsignacionOperativa", null)
                        .WithMany()
                        .HasForeignKey("IdAsignacionOperativa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asignaciones_operativas_permisos_asignaciones");

                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.PermisoOperativo", null)
                        .WithMany()
                        .HasForeignKey("IdPermisoOperativo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asignaciones_operativas_permisos_permisos");
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clientes_usuarios");
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.Direccion", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.Inquilino", null)
                        .WithMany()
                        .HasForeignKey("IdInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_direcciones_inquilinos");
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.Inquilino", null)
                        .WithMany()
                        .HasForeignKey("IdInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_empleados_inquilinos");

                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_empleados_usuarios");
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.EntidadFiscal", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.Inquilino", null)
                        .WithMany()
                        .HasForeignKey("IdInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entidades_fiscales_inquilinos");
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.Restaurante", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.Inquilino", null)
                        .WithMany()
                        .HasForeignKey("IdInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_restaurantes_inquilinos");
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.RoleInquilino", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.Inquilino", null)
                        .WithMany()
                        .HasForeignKey("IdInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_inquilino_inquilinos");
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.RoleInquilinoPermiso", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.PermisoInquilino", null)
                        .WithMany()
                        .HasForeignKey("IdPermisoInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_inquilino_permisos_permisos");

                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.RoleInquilino", null)
                        .WithMany()
                        .HasForeignKey("IdRoleInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_inquilino_permisos_roles");
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.RoleOperativo", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.Inquilino", null)
                        .WithMany()
                        .HasForeignKey("IdInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_operativos_inquilinos");
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.RoleOperativoPermiso", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.PermisoOperativo", null)
                        .WithMany()
                        .HasForeignKey("IdPermisoOperativo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_operativos_permisos_permisos");

                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.RoleOperativo", null)
                        .WithMany()
                        .HasForeignKey("IdRoleOperativo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_operativos_permisos_roles");
                });

            modelBuilder.Entity("RestauranteSaaS.Api.Domain.Entities.UnidadOperativa", b =>
                {
                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.Direccion", null)
                        .WithMany()
                        .HasForeignKey("IdDireccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unidades_operativas_direcciones");

                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.EntidadFiscal", null)
                        .WithMany()
                        .HasForeignKey("IdEntidadFiscal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unidades_operativas_entidades_fiscales");

                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.Inquilino", null)
                        .WithMany()
                        .HasForeignKey("IdInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unidades_operativas_inquilinos");

                    b.HasOne("RestauranteSaaS.Api.Domain.Entities.Restaurante", null)
                        .WithMany()
                        .HasForeignKey("IdRestaurante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unidades_operativas_restaurantes");
                });
#pragma warning restore 612, 618
        }
    }
}
