-- Entidades base para Identity, inquilinos, restaurantes y unidades operativas.
-- Convenciones:
--   - Tablas y columnas de dominio en espanol.
--   - Llaves foraneas con prefijo id_.
--   - Tablas internas de ASP.NET Identity conservan sus nombres esperados.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE "AspNetUsers"
(
    "Id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "UserName" VARCHAR(256) NULL,
    "NormalizedUserName" VARCHAR(256) NULL,
    "Email" VARCHAR(256) NULL,
    "NormalizedEmail" VARCHAR(256) NULL,
    "EmailConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
    "PasswordHash" TEXT NULL,
    "SecurityStamp" TEXT NULL,
    "ConcurrencyStamp" TEXT NULL,
    "PhoneNumber" TEXT NULL,
    "PhoneNumberConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
    "TwoFactorEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "LockoutEnd" TIMESTAMP WITH TIME ZONE NULL,
    "LockoutEnabled" BOOLEAN NOT NULL DEFAULT TRUE,
    "AccessFailedCount" INTEGER NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "AspNetRoles"
(
    "Id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "Name" VARCHAR(256) NULL,
    "NormalizedName" VARCHAR(256) NULL,
    "ConcurrencyStamp" TEXT NULL
);

CREATE TABLE "AspNetUserClaims"
(
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" UUID NOT NULL,
    "ClaimType" TEXT NULL,
    "ClaimValue" TEXT NULL,
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"
        FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id")
        ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins"
(
    "LoginProvider" TEXT NOT NULL,
    "ProviderKey" TEXT NOT NULL,
    "ProviderDisplayName" TEXT NULL,
    "UserId" UUID NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins"
        PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
        FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id")
        ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens"
(
    "UserId" UUID NOT NULL,
    "LoginProvider" TEXT NOT NULL,
    "Name" TEXT NOT NULL,
    "Value" TEXT NULL,
    CONSTRAINT "PK_AspNetUserTokens"
        PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"
        FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id")
        ON DELETE CASCADE
);

CREATE TABLE "AspNetRoleClaims"
(
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleId" UUID NOT NULL,
    "ClaimType" TEXT NULL,
    "ClaimValue" TEXT NULL,
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId")
        REFERENCES "AspNetRoles" ("Id")
        ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles"
(
    "UserId" UUID NOT NULL,
    "RoleId" UUID NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles"
        PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId")
        REFERENCES "AspNetRoles" ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId"
        FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id")
        ON DELETE CASCADE
);

CREATE TABLE inquilinos
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo VARCHAR(40) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'activo'
        CHECK (estado IN ('activo', 'inactivo', 'suspendido')),
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_inquilinos_codigo
        UNIQUE (codigo)
);

CREATE TABLE roles_inquilino
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_inquilino UUID NOT NULL,
    codigo VARCHAR(40) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_roles_inquilino_inquilinos
        FOREIGN KEY (id_inquilino)
        REFERENCES inquilinos(id),
    CONSTRAINT ux_roles_inquilino_inquilino_codigo
        UNIQUE (id_inquilino, codigo),
    CONSTRAINT ux_roles_inquilino_inquilino_nombre
        UNIQUE (id_inquilino, nombre)
);

CREATE TABLE permisos_inquilino
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo VARCHAR(100) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    descripcion TEXT NOT NULL,
    CONSTRAINT ux_permisos_inquilino_codigo
        UNIQUE (codigo)
);

CREATE TABLE roles_inquilino_permisos
(
    id_rol_inquilino UUID NOT NULL,
    id_permiso_inquilino UUID NOT NULL,
    CONSTRAINT pk_roles_inquilino_permisos
        PRIMARY KEY (id_rol_inquilino, id_permiso_inquilino),
    CONSTRAINT fk_roles_inquilino_permisos_roles
        FOREIGN KEY (id_rol_inquilino)
        REFERENCES roles_inquilino(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_roles_inquilino_permisos_permisos
        FOREIGN KEY (id_permiso_inquilino)
        REFERENCES permisos_inquilino(id)
        ON DELETE CASCADE
);

CREATE TABLE asignaciones_inquilino
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo VARCHAR(40) NOT NULL,
    id_usuario UUID NOT NULL,
    id_inquilino UUID NOT NULL,
    id_rol_inquilino UUID NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NULL,
    CONSTRAINT fk_asignaciones_inquilino_usuarios
        FOREIGN KEY (id_usuario)
        REFERENCES "AspNetUsers" ("Id"),
    CONSTRAINT fk_asignaciones_inquilino_inquilinos
        FOREIGN KEY (id_inquilino)
        REFERENCES inquilinos(id),
    CONSTRAINT fk_asignaciones_inquilino_roles
        FOREIGN KEY (id_rol_inquilino)
        REFERENCES roles_inquilino(id),
    CONSTRAINT ux_asignaciones_inquilino_codigo
        UNIQUE (codigo),
    CONSTRAINT ux_asignaciones_inquilino_usuario_inquilino_rol
        UNIQUE (id_usuario, id_inquilino, id_rol_inquilino)
);

CREATE TABLE asignaciones_inquilino_permisos
(
    id_asignacion_inquilino UUID NOT NULL,
    id_permiso_inquilino UUID NOT NULL,
    permitido BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_asignaciones_inquilino_permisos
        PRIMARY KEY (id_asignacion_inquilino, id_permiso_inquilino),
    CONSTRAINT fk_asignaciones_inquilino_permisos_asignaciones
        FOREIGN KEY (id_asignacion_inquilino)
        REFERENCES asignaciones_inquilino(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_asignaciones_inquilino_permisos_permisos
        FOREIGN KEY (id_permiso_inquilino)
        REFERENCES permisos_inquilino(id)
        ON DELETE CASCADE
);

CREATE TABLE roles_restaurante
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_inquilino UUID NOT NULL,
    codigo VARCHAR(40) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_roles_restaurante_inquilinos
        FOREIGN KEY (id_inquilino)
        REFERENCES inquilinos(id),
    CONSTRAINT ux_roles_restaurante_inquilino_codigo
        UNIQUE (id_inquilino, codigo),
    CONSTRAINT ux_roles_restaurante_inquilino_nombre
        UNIQUE (id_inquilino, nombre)
);

CREATE TABLE permisos_restaurante
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo VARCHAR(100) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    descripcion TEXT NOT NULL,
    CONSTRAINT ux_permisos_restaurante_codigo
        UNIQUE (codigo)
);

CREATE TABLE roles_restaurante_permisos
(
    id_rol_restaurante UUID NOT NULL,
    id_permiso_restaurante UUID NOT NULL,
    CONSTRAINT pk_roles_restaurante_permisos
        PRIMARY KEY (id_rol_restaurante, id_permiso_restaurante),
    CONSTRAINT fk_roles_restaurante_permisos_roles
        FOREIGN KEY (id_rol_restaurante)
        REFERENCES roles_restaurante(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_roles_restaurante_permisos_permisos
        FOREIGN KEY (id_permiso_restaurante)
        REFERENCES permisos_restaurante(id)
        ON DELETE CASCADE
);

CREATE TABLE restaurantes
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_inquilino UUID NOT NULL,
    codigo VARCHAR(40) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT NULL,
    logo_url TEXT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_restaurantes_inquilinos
        FOREIGN KEY (id_inquilino)
        REFERENCES inquilinos(id),
    CONSTRAINT ux_restaurantes_inquilino_codigo
        UNIQUE (id_inquilino, codigo)
);

CREATE TABLE asignaciones_restaurante
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo VARCHAR(40) NOT NULL,
    id_usuario UUID NOT NULL,
    id_restaurante UUID NOT NULL,
    id_rol_restaurante UUID NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NULL,
    CONSTRAINT fk_asignaciones_restaurante_usuarios
        FOREIGN KEY (id_usuario)
        REFERENCES "AspNetUsers" ("Id"),
    CONSTRAINT fk_asignaciones_restaurante_restaurantes
        FOREIGN KEY (id_restaurante)
        REFERENCES restaurantes(id),
    CONSTRAINT fk_asignaciones_restaurante_roles
        FOREIGN KEY (id_rol_restaurante)
        REFERENCES roles_restaurante(id),
    CONSTRAINT ux_asignaciones_restaurante_codigo
        UNIQUE (codigo),
    CONSTRAINT ux_asignaciones_restaurante_usuario_restaurante_rol
        UNIQUE (id_usuario, id_restaurante, id_rol_restaurante)
);

CREATE TABLE asignaciones_restaurante_permisos
(
    id_asignacion_restaurante UUID NOT NULL,
    id_permiso_restaurante UUID NOT NULL,
    permitido BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_asignaciones_restaurante_permisos
        PRIMARY KEY (id_asignacion_restaurante, id_permiso_restaurante),
    CONSTRAINT fk_asignaciones_restaurante_permisos_asignaciones
        FOREIGN KEY (id_asignacion_restaurante)
        REFERENCES asignaciones_restaurante(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_asignaciones_restaurante_permisos_permisos
        FOREIGN KEY (id_permiso_restaurante)
        REFERENCES permisos_restaurante(id)
        ON DELETE CASCADE
);

CREATE TABLE entidades_fiscales
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_inquilino UUID NOT NULL,
    rfc VARCHAR(13) NOT NULL,
    razon_social VARCHAR(200) NOT NULL,
    regimen_fiscal VARCHAR(120) NOT NULL,
    correo VARCHAR(256) NULL,
    telefono VARCHAR(30) NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_entidades_fiscales_inquilinos
        FOREIGN KEY (id_inquilino)
        REFERENCES inquilinos(id),
    CONSTRAINT ux_entidades_fiscales_rfc
        UNIQUE (rfc)
);

CREATE TABLE direcciones
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_inquilino UUID NOT NULL,
    pais VARCHAR(80) NOT NULL,
    estado VARCHAR(100) NOT NULL,
    municipio VARCHAR(100) NOT NULL,
    colonia VARCHAR(120) NOT NULL,
    codigo_postal VARCHAR(10) NOT NULL,
    calle VARCHAR(150) NOT NULL,
    numero_exterior VARCHAR(20) NOT NULL,
    numero_interior VARCHAR(20) NULL,
    referencia TEXT NULL,
    latitud NUMERIC(9,6) NULL,
    longitud NUMERIC(9,6) NULL,
    CONSTRAINT fk_direcciones_inquilinos
        FOREIGN KEY (id_inquilino)
        REFERENCES inquilinos(id)
);

CREATE TABLE unidades_operativas
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo VARCHAR(40) NOT NULL,
    id_inquilino UUID NOT NULL,
    id_restaurante UUID NOT NULL,
    id_entidad_fiscal UUID NOT NULL,
    id_direccion UUID NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_apertura DATE NULL,
    CONSTRAINT fk_unidades_operativas_inquilinos
        FOREIGN KEY (id_inquilino)
        REFERENCES inquilinos(id),
    CONSTRAINT fk_unidades_operativas_restaurantes
        FOREIGN KEY (id_restaurante)
        REFERENCES restaurantes(id),
    CONSTRAINT fk_unidades_operativas_entidades_fiscales
        FOREIGN KEY (id_entidad_fiscal)
        REFERENCES entidades_fiscales(id),
    CONSTRAINT fk_unidades_operativas_direcciones
        FOREIGN KEY (id_direccion)
        REFERENCES direcciones(id),
    CONSTRAINT ux_unidades_operativas_inquilino_codigo
        UNIQUE (id_inquilino, codigo)
);



CREATE TABLE empleados
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_usuario UUID NOT NULL,
    id_inquilino UUID NOT NULL,
    numero_empleado VARCHAR(50) NOT NULL,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    telefono VARCHAR(30) NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ux_empleados_inquilino_id_usuario
        UNIQUE (id_inquilino, id_usuario),
    CONSTRAINT ux_empleados_inquilino_numero_empleado
        UNIQUE (id_inquilino, numero_empleado),
    CONSTRAINT fk_empleados_usuarios
        FOREIGN KEY (id_usuario)
        REFERENCES "AspNetUsers" ("Id"),
    CONSTRAINT fk_empleados_inquilinos
        FOREIGN KEY (id_inquilino)
        REFERENCES inquilinos(id)
);

CREATE TABLE clientes
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_usuario UUID NOT NULL,
    codigo VARCHAR(40) NOT NULL,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    telefono VARCHAR(30) NULL,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_clientes_usuario
        UNIQUE (id_usuario),
    CONSTRAINT ux_clientes_codigo
        UNIQUE (codigo),
    CONSTRAINT fk_clientes_usuarios
        FOREIGN KEY (id_usuario)
        REFERENCES "AspNetUsers" ("Id")
);

CREATE TABLE roles_operativos
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_inquilino UUID NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL,
    CONSTRAINT fk_roles_operativos_inquilinos
        FOREIGN KEY (id_inquilino)
        REFERENCES inquilinos(id),
    CONSTRAINT ux_roles_operativos_inquilino_nombre
        UNIQUE (id_inquilino, nombre)
);

CREATE TABLE permisos_operativos
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo VARCHAR(100) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    descripcion TEXT NOT NULL,
    CONSTRAINT ux_permisos_operativos_codigo
        UNIQUE (codigo)
);

CREATE TABLE asignaciones_operativas
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo VARCHAR(40) NOT NULL,
    id_empleado UUID NOT NULL,
    id_unidad_operativa UUID NOT NULL,
    id_rol_operativo UUID NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NULL,
    CONSTRAINT fk_asignaciones_operativas_empleados
        FOREIGN KEY (id_empleado)
        REFERENCES empleados(id),
    CONSTRAINT fk_asignaciones_operativas_unidades_operativas
        FOREIGN KEY (id_unidad_operativa)
        REFERENCES unidades_operativas(id),
    CONSTRAINT fk_asignaciones_operativas_roles_operativos
        FOREIGN KEY (id_rol_operativo)
        REFERENCES roles_operativos(id),
    CONSTRAINT ux_asignaciones_operativas_codigo
        UNIQUE (codigo),
    CONSTRAINT ux_asignaciones_operativas_empleado_unidad_rol
        UNIQUE (id_empleado, id_unidad_operativa, id_rol_operativo)
);

CREATE TABLE roles_operativos_permisos
(
    id_rol_operativo UUID NOT NULL,
    id_permiso_operativo UUID NOT NULL,
    CONSTRAINT pk_roles_operativos_permisos
        PRIMARY KEY (id_rol_operativo, id_permiso_operativo),
    CONSTRAINT fk_roles_operativos_permisos_roles
        FOREIGN KEY (id_rol_operativo)
        REFERENCES roles_operativos(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_roles_operativos_permisos_permisos
        FOREIGN KEY (id_permiso_operativo)
        REFERENCES permisos_operativos(id)
        ON DELETE CASCADE
);

CREATE TABLE asignaciones_operativas_permisos
(
    id_asignacion_operativa UUID NOT NULL,
    id_permiso_operativo UUID NOT NULL,
    permitido BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_asignaciones_operativas_permisos
        PRIMARY KEY (id_asignacion_operativa, id_permiso_operativo),
    CONSTRAINT fk_asignaciones_operativas_permisos_asignaciones
        FOREIGN KEY (id_asignacion_operativa)
        REFERENCES asignaciones_operativas(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_asignaciones_operativas_permisos_permisos
        FOREIGN KEY (id_permiso_operativo)
        REFERENCES permisos_operativos(id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX idx_roles_inquilino_inquilino ON roles_inquilino(id_inquilino);
CREATE INDEX idx_roles_inquilino_activo ON roles_inquilino(activo);
CREATE INDEX idx_roles_inquilino_permisos_permiso ON roles_inquilino_permisos(id_permiso_inquilino);
CREATE INDEX idx_asignaciones_inquilino_usuario ON asignaciones_inquilino(id_usuario);
CREATE INDEX idx_asignaciones_inquilino_inquilino ON asignaciones_inquilino(id_inquilino);
CREATE INDEX idx_asignaciones_inquilino_rol ON asignaciones_inquilino(id_rol_inquilino);
CREATE INDEX idx_asignaciones_inquilino_activo ON asignaciones_inquilino(activo);
CREATE INDEX idx_asignaciones_inquilino_permisos_permiso ON asignaciones_inquilino_permisos(id_permiso_inquilino);
CREATE INDEX idx_roles_restaurante_inquilino ON roles_restaurante(id_inquilino);
CREATE INDEX idx_roles_restaurante_activo ON roles_restaurante(activo);
CREATE INDEX idx_roles_restaurante_permisos_permiso ON roles_restaurante_permisos(id_permiso_restaurante);
CREATE INDEX idx_restaurantes_inquilino ON restaurantes(id_inquilino);
CREATE INDEX idx_restaurantes_activo ON restaurantes(activo);
CREATE INDEX idx_asignaciones_restaurante_usuario ON asignaciones_restaurante(id_usuario);
CREATE INDEX idx_asignaciones_restaurante_restaurante ON asignaciones_restaurante(id_restaurante);
CREATE INDEX idx_asignaciones_restaurante_rol ON asignaciones_restaurante(id_rol_restaurante);
CREATE INDEX idx_asignaciones_restaurante_activo ON asignaciones_restaurante(activo);
CREATE INDEX idx_asignaciones_restaurante_permisos_permiso ON asignaciones_restaurante_permisos(id_permiso_restaurante);
CREATE INDEX idx_entidades_fiscales_inquilino ON entidades_fiscales(id_inquilino);
CREATE INDEX idx_entidades_fiscales_activo ON entidades_fiscales(activo);
CREATE INDEX idx_direcciones_inquilino ON direcciones(id_inquilino);
CREATE INDEX idx_unidades_operativas_inquilino ON unidades_operativas(id_inquilino);
CREATE INDEX idx_unidades_operativas_restaurante ON unidades_operativas(id_restaurante);
CREATE INDEX idx_unidades_operativas_entidad_fiscal ON unidades_operativas(id_entidad_fiscal);
CREATE INDEX idx_unidades_operativas_direccion ON unidades_operativas(id_direccion);
CREATE INDEX idx_unidades_operativas_activo ON unidades_operativas(activo);
CREATE INDEX idx_empleados_usuario ON empleados(id_usuario);
CREATE INDEX idx_empleados_inquilino ON empleados(id_inquilino);
CREATE INDEX idx_empleados_activo ON empleados(activo);
CREATE INDEX idx_clientes_usuario ON clientes(id_usuario);
CREATE INDEX idx_roles_operativos_inquilino ON roles_operativos(id_inquilino);
CREATE INDEX idx_asignaciones_operativas_empleado ON asignaciones_operativas(id_empleado);
CREATE INDEX idx_asignaciones_operativas_unidad_operativa ON asignaciones_operativas(id_unidad_operativa);
CREATE INDEX idx_asignaciones_operativas_rol_operativo ON asignaciones_operativas(id_rol_operativo);
CREATE INDEX idx_asignaciones_operativas_activo ON asignaciones_operativas(activo);
CREATE INDEX idx_roles_operativos_permisos_permiso ON roles_operativos_permisos(id_permiso_operativo);
CREATE INDEX idx_asignaciones_operativas_permisos_permiso ON asignaciones_operativas_permisos(id_permiso_operativo);
